emailDbUrl: http://mangosteen-es2.cloudapp.net:9200/emails-final/email/_search
dateServiceUrl: http://mangosteen-datetime.azurewebsites.net
contactUrl: http://mangosteen-es2.cloudapp.net:9200/emails-final/_suggest
suggestUrl: http://mangosteen-es2.cloudapp.net:9200/emails-final/_suggest
