emailDbUrl: http://mangosteen-es.cloudapp.net:9200/emails-test101/email/_search
dateServiceUrl: http://mangosteen-datetime.azurewebsites.net
contactUrl: http://mangosteen-es.cloudapp.net:9200/emails-test101/_suggest
